# Generated by Django 4.0.5 on 2022-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='treiler',
            field=models.CharField(max_length=300, null=True, verbose_name='Трейлер'),
        ),
    ]
