# Generated by Django 4.0.5 on 2022-06-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_treiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(null=True, upload_to='movies/banner/', verbose_name='Банер'),
        ),
    ]
