# Generated by Django 4.0.5 on 2022-06-27 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='films',
            field=models.FileField(null=True, upload_to='movies/films/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Файл фільму'),
        ),
    ]
