# Generated by Django 4.0.5 on 2022-06-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='treiler',
            field=models.URLField(max_length=300, null=True, verbose_name='Трейлер'),
        ),
    ]
