# Generated by Django 4.0.5 on 2022-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_treiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_small',
            field=models.CharField(max_length=80, null=True, verbose_name='Описання коротко'),
        ),
    ]
