# Generated by Django 4.0.5 on 2022-06-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_description_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description_small',
            field=models.CharField(max_length=100, null=True, verbose_name='Описання коротко'),
        ),
    ]
