# Generated by Django 4.0.5 on 2022-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_description_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='films',
            field=models.URLField(max_length=300, null=True, verbose_name='Фільм'),
        ),
    ]
