# Generated by Django 4.0.5 on 2022-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_films'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time_h',
            field=models.IntegerField(default=1, verbose_name='Години'),
        ),
        migrations.AddField(
            model_name='movie',
            name='time_m',
            field=models.IntegerField(default=1, verbose_name='Хвилини'),
        ),
    ]
