# Generated by Django 4.0.5 on 2022-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_time_h_movie_time_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description_small',
            field=models.CharField(max_length=88, null=True, verbose_name='Описання коротко'),
        ),
    ]
