# Generated by Django 4.0.5 on 2022-07-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_reviews_movie_remove_reviews_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Чернетка'),
        ),
    ]
