# Generated by Django 4.0.5 on 2022-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_reviews_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='loc',
            field=models.CharField(max_length=100, null=True, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Повідомлення'),
        ),
    ]
