# Generated by Django 4.0.5 on 2022-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_reviews_last_name_reviews_loc_alter_reviews_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name="Ім'я"),
        ),
    ]
